config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create]
  resources :posts
  resources :likes
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "posts#index"

  get "/profiles/:user_id", to: "profiles#show", as: :profile
  get "/profiles", to: "profiles#index"
  get "/friends", to: "profiles#friends"

  post "follow/account", to: "profiles#follow_account", as: :follow_account
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true
  belongs_to :user
  belongs_to :post
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :profile, optional: true

  validates_uniqueness_of :friend_1_id, scope: :friend_2_id

end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness: { scope: [:likeable_id, :likeable_type]}
  belongs_to :user
  belongs_to :likeable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  has_many :comments
  has_many :likes, as: :likeable, dependent: :destroy
  belongs_to :profile, optional: true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :User
  has_many :posts
  has_many :friends
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  has_many :posts
  has_many :comments
  has_many :likes, dependent: :destroy
  has_one :profile
  has_many :friends

  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :authenticate_user!


  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

        respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json

  # DELETE /comments/1 or /comments/1.json
  # def destroy
  #   @comment.destroy
  #
  #   respond_to do |format|
  #     format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    # def set_comment
    #   @comment = Comment.find(params[:id])
    # end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :post_id)
    end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def index
    friends_ids = Friend.where(friend_1_id: current_user.id).map(&:friend_2_id)
    friends_ids << current_user.id
    @friends = User.where.not(id: friends_ids).where.not(id:current_user.id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.new(like_params)

    if !@like.save
      flash[:notice] = @like.errors.full_messages.to_sentence
    end

    redirect_back(fallback_location: posts_url)
  end

  def destroy
    @like=  current_user.likes.find(params[:id])
    @like.destroy
    redirect_back(fallback_location: posts_url)
  end


  private

  def like_params
    params.require(:like).permit(:likeable_id, :likeable_type)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts or /posts.json
  def index
    friends_ids = Friend.where(friend_1_id: current_user.id).map(&:friend_2_id)
    friends_ids << current_user.id

    @posts = Post.includes(:user).where(user_id: friends_ids).order("created_at DESC")
    @post = Post.new
    @comment = Comment.new
  end

  # GET /posts/1 or /posts/1.json
  def current_post
    @current_post ||= Post.find(session[:post_id]) if session[:post_id]
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  #before_action :set_post, only: %i[ show edit update destroy ]
  before_action :set_profile, only: [:show]

  def index
    @profiles = User.where.not(id:current_user.id)
    friends_ids = Friend.where(friend_1_id: current_user.id).map(&:friend_2_id)
    friends_ids << current_user.id

    @friends_post = Post.includes(:user).where(user_id: friends_ids)
    @fe = User.where(id: friends_ids).where.not(id:current_user.id)
  end

  def show
  end

  def follow_account
    account_id = params[:follow_id]
    if Friend.create!(friend_1_id: current_user.id, friend_2_id: account_id)
      flash[:success] = 'Friend Added!'
    else
      flash[:danger] = 'Unable to add friend!'
    end
    redirect_to profiles_path
  end

  def set_profile
    @profile = User.find_by_id(params[:user_id])
  end


  private
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_for  @comment,:html => {:class => 'form'} do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :body, class:"form-input", size:"60", placeholder:"Write a comment..."%>
  </div>
  <div class="field">
    <%= form.number_field :user_id, class:"form-input", size:"60", placeholder:"Write a comment...", value:current_user.id%>
  </div>
  <div class="field">
    <%= form.number_field :post_id, class:"form-input", size:"60", placeholder:"Write a comment...", value:post.id%>
  </div>
  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fakebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/likes/_button.html.erb
<% like = current_user.likes.find_by(likeable: likeable) %>
<% if like.nil? %>
  <form action="/likes" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="like[likeable_id]" value="<%= likeable.id %>">
    <input type="hidden" name="like[likeable_type]" value="<%= likeable.class.to_s %>">
    <input type="submit" value="Like" class="btn-like">
  </form>
<% else %>
  <form action="<%= like_path(like) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Unlike" class="btn-like">
  </form>
<% end %>

app/views/posts/_feed.html.erb
<div class="feed-container ">
<div class="profile-img "></div>
<%= form_for @post,:html => {:class => 'form'}  do |form|%>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
    <div class="input-group py-4 px-3">
    <%= form.text_field :content, class:"form-control", size:"50", placeholder: "What's on your mind, #{current_user.first_name}"%>
    <%= form.submit class:"btn btn-primary" %>
    </div>
<% end %>
</div>
<br>
<% unless @posts.nil? %>
<div class="container-sm">
  <% @posts.each do |post| %>
<div class="card">
      <div class="profile ps-4">
        <div class="profile-img"></div>
        <p class="username"><%= post.user.first_name %> <%= post.user.last_name  %></p>
        <% if current_user.id == post.user.id %>
      <div class="dropdown">
          <button class="btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" >
            <%= inline_svg_tag "dots-y-svgrepo-com", class: 'icon dots' %>
          </button>
          <ul class="dropdown-menu" >
            <li><%= link_to "Edit", edit_post_path(post), class:"dropdown-item" %>
            <li><%= link_to "Delete", post_path(post), data: { confirm: "Are you sure you want to delete this post?" } , :method => :delete, class:"dropdown-item" %>
            </li>
          </ul>
        </div>
        <% end %>
      </div>
          <div class="card-body py-0">
        <p class="ps-3 py-0 fs-6" style="color:#65676b"><%= post.created_at.strftime("%B %d, %Y") %></p>
        <p class="fs-4 ps-3"><%= post.content  %></p>
        <p class="ps-3">
          <%= post.likes.count == 1 ? "#{post.likes.count} like" : "#{post.likes.count} likes" %>
        </p>
      </div>
      <div class="interaction mx-3">
      <%= render partial: "likes/button", locals: {likeable: post} %>
        <div class="comment-btn">Comment</div>
      </div>
      <div class="comment-section">
        <div class="container-sm ">
          <% post.comments.each do |comment| %>
            <div class="comment ps-4 me-4">
              <strong><%= comment.user.first_name %> <%= comment.user.last_name %></strong><br>
              <p class="mb-1"><%= comment.body%></p>
              <%= comment.likes.count == 1 ? "#{comment.likes.count} like" : "#{comment.likes.count} likes" %>
              <%= render partial: "likes/button", locals: {likeable: comment} %>
            </div>
            <br>
        <% end %>
        </div>
        <%= form_for  @comment do |form| %>
          <div class="input-group mb-4 px-3 pl-3">
            <%= form.text_field :body, class:"form-control", placeholder:"Write a comment..."%>
            <%= form.hidden_field :post_id, value:post.id%>
            <%= form.hidden_field :user_id, value:current_user.id%>
            <%=form.submit "Post", class:"btn btn-outline-primary" %>
          </div>
        <% end %>
      </div>
    </div>
    <br>
  <% end %>
</div>
  <% else %>
  <h3 class="text-center ">No posts :(</h3>
<% end %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    </button>
    <div class="collapse navbar-collapse position-relative" id="navbarSupportedContent">
      <form class="d-flex">
        <%= inline_svg_tag "letter-f-svgrepo-com", class: 'logo' %>
        <input class="form-control me-2 search" type="search" placeholder="Search Fakebook" aria-label="Search">
    </form>
      <ul class="navbar-menu">
        <li class="nav-item item">
          <a class="nav-link" href="/posts">
            <%= inline_svg_tag "home-svgrepo-com.svg", class: 'icon' %>
          </a>
        </li>
        <li class="nav-item item">
          <a class="nav-link" aria-current="page" href="/profiles">
            <%= inline_svg_tag "two-friends-svgrepo-com ", class: 'icon dropdown' %>
          </a>
        </li>
        <li class="nav-item item">
          <a class="nav-link" href="#">
            <%= inline_svg_tag "multiple-screen-play-svgrepo-com", class: 'icon' %>
          </a>
        </li>
        <li class="nav-item item">
          <a class="nav-link" href="#">
            <%= inline_svg_tag "game-svgrepo-com", class: 'icon' %>
          </a>
        </li>
      </ul>
      <ul class="profile-menu">
        <li class="nav-item">
        <a class="user" href="/profiles/<%= current_user.id %>">
            <div class="profile-menu-img"></div>
            <p class="profile-menu-username"><%= current_user.first_name %></p>
            </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <%= inline_svg_tag "message-svgrepo-com", class: 'profiles-menu-icon' %>
          </a>
        </li><li class="nav-item">
        <a class="nav-link" href="#">
          <%= inline_svg_tag "bell-svgrepo-com", class: 'profiles-menu-icon' %>
        </a>
      </li>
        <li class="nav-item">
          <div class="dropdown">
            <button class="btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
              <%= inline_svg_tag "arrow-down-bold-svgrepo-com", class: 'profiles-menu-icon' %>
            </button>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton1">
              <li><%= link_to "Create", new_post_path, class:"dropdown-item" %>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete,  class:"dropdown-item" %>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render "posts/header" %>
<p id="notice"><%= notice %></p>
<br>
<%= render "posts/feed" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong><br>
  <p><% @post.content %></p>
  <%= render partial: "likes/button", locals: {likeable: @post} %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/profiles/_suggestions.html.erb
<div class="row mx-1">
  <div class="col-2">
    <div class="d-flex flex-column">
      <h2>Friends</h2>
      <%= link_to "Home", '/profiles', class:"p-2" %>
      <%= link_to "Suggestions", '/friends', class:"p-2" %>
      <a href="#" class="p-2">Birthdays</a>
    </div>
  </div>
  <div class="col-10">
    <div class="text-center friends">
      <h2 class="text-center py-3"><%= title %></h2>
      <div class="d-flex justify-content-evenly">
        <% page.each do |user|%>
          <div class="card d-flex align-items-center fd-column" >
            <div class="friend-card-img "></div>
            <div class="card-body px-0">
              <h5 class="card-title"><%= user.first_name%> <%= user.last_name%></h5>
              <p class="card-text"></p>
              <div class="d-flex justify-content-between ">
                <%= link_to "View profile", profile_path(user.id), class:"btn btn-primary me-3" %>
                <% if (Friend.where(friend_1_id: current_user.id).map(&:friend_2_id).include? user.id) == false %>
                  <%= form_tag follow_account_path, method: :post do %>
                    <%= hidden_field_tag :follow_id, user.id %>
                    <%= submit_tag "Add Friend", class:"btn btn-primary" %>
                  <% end %>
                <% else %>
                  <p class="my-0 py-2">Already Friends</p>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/friends.html.erb
<%= render "posts/header" %>
<%friends_ids = Friend.where(friend_1_id: current_user.id).map(&:friend_2_id)%>
<% friends_ids << current_user.id%>
<% @friends = User.where.not(id: friends_ids).where.not(id:current_user.id) %>
<%= render partial: "suggestions", locals: {page: @friends, title: "Suggestions"}%>

app/views/profiles/index.html.erb
<%= render "posts/header" %>
<%= render partial: "suggestions", locals: {page: @fe, title:"Friends"}%>

app/views/profiles/show.html.erb
<%= render 'posts/header' %>
<div class="d-flex bd-highlight justify-content-center">
  <div class="cover-img"></div>
  <div class="profile-photo"></div>
</div>
<div class="d-flex p-2 bd-highlight justify-content-between align-items-center temp pb-4">
  <h2 class="profile-usernmae fw-bolder"><%=@profile.first_name %> <%=@profile.last_name %></h2>
  <% if (Friend.where(friend_1_id: current_user.id).map(&:friend_2_id).include? @profile.id) == false %>
    <%= link_to "Edit Profile", edit_user_registration_path, class:"btn btn-primary"  %>
    <% else %>
  <% if (Friend.where(friend_1_id: current_user.id).map(&:friend_2_id).include? @profile.id) == false %>
    <%= form_tag follow_account_path, method: :post do %>
      <%= hidden_field_tag :follow_id, @profile.id %>
      <%= submit_tag "Add Friend", class:"btn btn-primary" %>
    <% end %>
  <% else %>
    <p class="my-0 py-2">Already Friends</p>
  <% end %>
    <% end %>
</div>
<div class="container">
  <nav class="navbar navbar-expand-lg navbar-primary navbar-temp mx-auto">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Posts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Friends</a>
          </li>
          <li class="nav-item">
            <a class="nav-link ">Photos</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Videos</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

<div class="d-flex p-2 bd-highlight align-items-center temp ">
  <div class="d-flex flex-column container justify-content-start align-self-start">
    <div class="bio card mb-3 p-4">
      <h2 class="pb-3">Intro</h2>
      <p>Lives in <strong>Belgrade</strong>.</p>
      <p>Works at <strong>DODO STT</strong>.</p>
      <p>Studied at <strong>College of Tourism</strong>.</p>
    </div>
    <div class="bio card mb-3 p-4" >
      <h2 class="pb-3">Friends</h2>
      <div class="row mx-0">
      <% friends_ids = Friend.where(friend_1_id: @profile.id).map(&:friend_2_id)%>
      <% friends_ids << current_user.id%>
      <% User.where(id: friends_ids).each do |user|%>
        <div class="card align-items-center col-6 m-2 p-0" style="width: 180px">
          <div class="friend-card-img-sm d-flex align-items-end">
            <h6 class="card-title md-0 ps-2" style="color:#fff"><%= user.first_name%> <%= user.last_name%></h6>
          </div>
          <div class="card-body px-0">
              <%= link_to "View profile", profile_path(user.id), class:"btn btn-primary btn-sm me-3" %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
    <div class="bio card mb-3 p-4">
      <h2 class="pb-3">Photos</h2>
    </div>
  </div>
  <div class="container align-self-start">
<!--    <div class="feed-container ">-->
<!--      <div class="profile-img "></div>-->
      <%#= form_for @post, :url => { controller: "posts", :action => "new" }, :html => {:class => 'form'}  do |form|%>
        <%# if @post.errors.any? %>
<!--          <div id="error_explanation">-->
<!--            <h2><%#= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>-->
<!--            <ul>-->
              <%# @post.errors.each do |error| %>
<!--                <li><%#= error.full_message %></li>-->
              <%# end %>
<!--            </ul>-->
<!--          </div>-->
        <%# end %>
<!--        <div class="input-group py-4 px-3">-->
          <%#= form.text_field :content, class:"form-control", size:"50", placeholder: "What's on your mind, Filip?"%>
          <%#= form.submit class:"btn btn-primary" %>
<!--        </div>-->
      <%# end %>
<!--    </div>-->
    <h2 class="text-start p-3 card ">Posts</h2>
    <% @profile.posts.each do |post| %>
      <div class="card">
        <div class="profile ps-4">
          <div class="profile-img"></div>
          <p class="username"><%= post.user.first_name %> <%= post.user.last_name  %></p>
          <div class="dropdown">
            <button class="btn" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" >
              <%= inline_svg_tag "dots-y-svgrepo-com", class: 'icon dots' %>
            </button>
            <ul class="dropdown-menu" >
              <li><%= link_to "Edit", edit_post_path(post), class:"dropdown-item" %>
              <li><%= link_to "Delete", post_path(post), data: { confirm: "Are you sure you want to delete this post?" } , :method => :delete, class:"dropdown-item" %>
              </li>
            </ul>
          </div>
        </div>
        <div class="card-body py-1 ">
          <p class="ps-3 py-0 fs-6" style="color:#65676b"><%= post.created_at.strftime("%B %d, %Y") %></p>
          <p class="fs-4 ps-3"><%= post.content  %></p>
        </div>
        <div class="interaction mx-3">
          <div class="like">Like</div>
          <div class="comment-btn">Comment</div>
        </div>
      </div>
      <br>
    <% end %>
  </div>
</div>